# -*- coding: utf-8 -*-
"""Prueba_obtencion_datos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/130o0klK-93At5475iE6LIKV2XF1pnC7n
"""

import pandas as pd

# datos de empleados
data_empleados = {
    'id_empleado': [101, 102, 103, 104, 105, 106, 107, 108],
    'nombre': ['Ana', 'Luis', 'Sofía', 'Carlos', 'Elena', 'Pedro', 'Laura', 'David'],
    'salario': [55000, 58000, 72000, 48000, 75000, 85000, 62000, 88000],
    'id_departamento': ['V_01', 'V_01', 'T_01', 'M_01', 'T_01', 'D_01', 'M_01', 'D_01']
}

df_empleados = pd.DataFrame(data_empleados)

# datos de departamentos
data_departamentos = {
    'id_departamento': ['V_01', 'T_01', 'M_01', 'D_01'],
    'nombre_depto': ['Ventas', 'Tecnología', 'Marketing', 'Dirección'],
    'ubicacion': ['Norte', 'Sur', 'Norte', 'Norte']
}

df_departamentos = pd.DataFrame(data_departamentos)

# unir los datos
df_completo = pd.merge(df_empleados, df_departamentos, on='id_departamento', how='left')

print("DataFrame completo:")
print(df_completo)

# agrupar por departamento y ubicación
resumen = df_completo.groupby(['nombre_depto', 'ubicacion'])['salario'].mean().reset_index()

print("\nSalario promedio por departamento y ubicación:")
print(resumen)

# tabla pivote
tabla_pivote = resumen.pivot(index='nombre_depto', columns='ubicacion', values='salario')

print("\nTabla pivote final:")
print(tabla_pivote)